trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: Test
  env:
    SCD_Access: $(GitHubPAT) # the recommended way to map to an env variable
  inputs:
    command: 'test'
